name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/api/**'
      - 'apps/electron/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'apps/api/**'
      - 'apps/electron/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6
          run_install: false

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies for API
        working-directory: ./apps/api
        run: pnpm install

      - name: Lint API
        working-directory: ./apps/api
        run: pnpm lint

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6
          run_install: false

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Format Check
        run: pnpm format:check

  test:
    name: Test - macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Base Ref
        if: github.event_name == 'pull_request'
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.6
          run_install: false

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install dependencies and run tests for API
        working-directory: ./apps/api
        run: |
          pnpm install
          pnpm test

      - name: Install dependencies and run tests for Electron
        working-directory: ./apps/electron
        run: |
          pnpm install
          pnpm test
